pipeline {
    agent any
    environment {
        CI = false
    }
    stages {
        //stage('Git checkout') {
         //   steps{
                // Get source code from a GitHub repository
         //       git branch:'main', url:'https://github.com/Christina-29/BookingLet.git'
           // }
        //}
        
        stage('npm install') {
            steps{
                dir('./front_end/') {
                    sh 'npm install'
                }
            }
        }
        stage('npm build') {
            steps{
                dir('./front_end/') {
                    sh 'npm run build'
                }
            }
        }
        stage('artifacts to s3') {
            steps{
                withAWS(region: 'ap-southeast-2', credentials : 'christina'){
                dir('./front_end/') {
                  sh 'aws s3 ls'
                  sh 'aws s3 sync /var/lib/jenkins/jobs/frontend/builds s3://www.she-can.tech'}
                }
            }
        }
    }
}
