import food from '../../../../assets/food.jpg';

const Data = [
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
  {
    image: food,
    name: 'Sushi Bar',
    address: '2000 Sydney NSW',
    addPpl: '354 people add to booklet',
    desc: 'Sushi is perhaps the most famous Japanese food in the world. Sushi is defined as any dish that is made with vinegared sushi rice.',
    link: '',
  },
];

export default Data;
