FROM node:16.0.0

WORKDIR /usr/src/app
#set working directory

COPY package*.json ./
#in current directory cp package.json to WORKDIR

RUN npm install 
#run this command when docker build

COPY . .

EXPOSE 8000
#expose port 8000

CMD ["npm", "run", "start"]
#run this command when docker run
