pipeline {
    agent any
    environment {
        AWS_ACCOUNT_ID="544863999112"
        AWS_DEFAULT_REGION="ap-southeast-2" 
	    CLUSTER_NAME="default1"
	    SERVICE_NAME="backend-container-service"
	    TASK_DEFINITION_NAME="first-run-task-definition:6"
	    DESIRED_COUNT="1"
        IMAGE_REPO_NAME="demo"
        IMAGE_TAG="latest"
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}"
	registryCredential = "christina"
    }
   
    stages {
      stage('npm install') {
            steps{
                dir('./back_end/') {
                    sh 'npm install'
                }
            }
        }
        
    // Building Docker images
    stage('Building image') {
      steps{
        dir('./back_end'){
          sh 'docker build -t demo .' }
        }
    }

    // Uploading Docker images into AWS ECR
    stage('Pushing to ECR') {
     steps{  
        dir('./back_end'){
           sh 'docker tag demo:latest 544863999112.dkr.ecr.ap-southeast-2.amazonaws.com/demo:latest'
           sh 'docker push 544863999112.dkr.ecr.ap-southeast-2.amazonaws.com/demo:latest' }
        }
    }
      
    stage('Deploy') {
     steps{
        dir('./back_end'){
            withAWS(credentials: registryCredential, region: "${AWS_DEFAULT_REGION}") {
			sh './script.sh' }
            } 
        }
      }       
    }
}